### ISSUE TITLE
[v1.0.0] Backlog de tarefas

### ISSUE THREAD

**Issue by diego3g** [diego3g/rsxp-2023#49]
Fala devs! 🔥

Estou criando essa issue para mapearmos todas tarefas para atingirmos a versão 1.0.0 do app conforme o [layout](https://www.figma.com/file/mSZqH7CG5fXBO0jsHMyMts/RS%2FXP-23-App?node-id=82-359&t=XJrrcy2K0zvfYQPo-0).

Quer contribuir com alguma das tarefas abaixo? Crie uma issue nesse repositório com o título da tarefa conforme a listagem abaixo e, se houver qualquer dúvida sobre o resultado esperado, utilize a label `help wanted` para que mais pessoas possam contribuir na discussão de como aquela funcionalidade vai se comportar.

> ⚠️ Antes de criar a issue, verifique se não existe uma outra issue com a mesma tarefa (localize pelo número da task).

> 👀 Sentiu que faltou alguma task aqui? Deixe um comentário para adicionarmos.

## Core

- [ ] [0001] Configuração de workflows de CI para linting e type checking
- [ ] [0002] Padronização de commits utilizando commitlint (#46)

## Design

- [ ] [0003] Imagem de compartilhamento de credencial nas redes sociais
- [ ] [0004] Tela com listagem de caravanas por região e link para formulário de inscrição por região (Por enquanto: Pará, Alagoas, Rio de Janeiro, Minas Gerais, Paraná e Pernambuco)

## Mobile

- [x] [0005] Configuração do ícone e splash screen do app (#44)
- [x] [0006] Configurção base do Expo Router (#41)
- [x] [0007] Configuração do tema e cores (#43)
- [ ] [0008] Autenticação via Github
- [ ] [0009] Layout do cabeçalho e menu em abas
- [ ] [0010] Layout do menu de navegação
- [ ] [0011] Layout da página de "Minha credencial"
- [ ] [0012] Configuração do React Query
- [ ] [0013] Configuração de mocks para chamadas HTTP

## Server

> ⚠️ Várias funcionalidades do back-end dependem da autenticação em que estamos trabalhando internamente na Rocketseat, por exemplo, o vínculo do ingresso precisa ser com o usuário logado e, enquanto essa funcionalidade não existe, podemos descartar a necessidade da referência ao usuário nas tabelas do banco.

- [ ] [0014] Serviço de conexão com a [API do Sympla](https://www.sympla.com.br/api-doc/index.html)
- [ ] [0015] Vincular ingresso
- [ ] [0016] Remover ingresso
- [ ] [0017] Buscar ingresso vinculado
- [ ] [0018] Rota de "Minha credencial"

**Comment by LuizHAP** [comment]
Acabei ficando com uma dúvida geral @diego3g , todas as tasks terão testes unitários? Se sim, precisamos adicionar uma task para configurar o jest

**Comment by RennanD** [comment]
@diego3g acho faltou o layout da página de "ingresso".

**Comment by eugustavo** [comment]
Olá @diego3g! Tudo certo?

Não sei ao certo se isso seria classificado como uma task, mas olhando aqui, parece que me faltou a implementação do ticket na Wallet. Se caso esse item virar uma task, gostaria de me desafiar a implementa-lá 🚀

**Comment by diego3g** [comment]
@eugustavo Total! Vou criar a task ali no board!

**Comment by jorge-lba** [comment]
@diego3g vi no figma que temos uma pagina de convite por email, acredito que se definirmos uma ferramenta para isso daria para ir adiantando alguma coisa de back em quanto estão trabalhando na autenticação.

Sei que é uma funcionalidade para depois do MVP, mas acredito que com a task alguma back que esta aguardando poderia dar inicio.

**Comment by diego3g** [comment]
@jorge-lba você pode ir pensando nisso se quiser, mas não vou nem adicionar isso no backlog porque, como tu mesmo falou, não vai entrar na primeira versão.

**Comment by vinifraga** [comment]
Quando puder @diego3g edita os status das tasks pra gente por favor, assim sabemos quais estão pendentes 💜
